/* All player-facing text lives in string tables (GDD §13). English is the
   hand-written original; the other six are AI-translated (see the in-product
   disclaimer in Settings/About). Classic script + window globals on purpose:
   the game must run from file://, which blocks ES modules and fetch() of JSON.

   UI chrome is translated below. Narrative content (Herald copy, dialogue,
   Tome entries) is translated with its content milestones, not here.
   The ph.* placeholder notes are dev scaffolding and stay English. */

/* ---- BUILD STAMP (single source of truth) ----------------------------------
   ONE integer identifies the build. It appears in exactly two places:
     1. window.BUILD.n below  → rendered as the visible title-corner stamp.
     2. The ?v=<n> cache token on every <link>/<script> in index.html, css/main.css
        and cap/index.html (the share page — added §R16; it loads the game's own
        nightcap.js, so a stale copy there breaks a shared link after a redeploy).
   THESE MUST MATCH. On every commit, bump ALL in lockstep:
     • strings.js : BUILD.n → next integer, BUILD.date → today (DD-MM).
     • index.html + css/main.css + cap/index.html :
         find-replace  ?v=<old>  →  ?v=<new>  (all occurrences).
   The stamp is how a real player (and Tessa) confirms which build loaded — the
   06-07 P0 was a stale cached build; this makes that visible at a glance. The
   optional .hash is a git short-hash pasted in AFTER commit if wanted. */
window.BUILD = { n: 41, date: "11-07", hash: "" };

/* buildLabel() — the exact text shown in the title corner, e.g. "v9 · 06-07". */
window.buildLabel = function () {
  var b = window.BUILD || { n: "?", date: "" };
  var s = "v" + b.n;
  if (b.date) s += " · " + b.date;
  if (b.hash) s += " · " + b.hash;
  return s;
};

window.LANGS = [
  { code: "en", native: "English" },
  { code: "ko", native: "한국어" },
  { code: "ja", native: "日本語" },
  { code: "de", native: "Deutsch" },
  { code: "es", native: "Español" },
  { code: "fr", native: "Français" },
  { code: "pt", native: "Português" },
];

window.STRINGS = {
  en: {
    "title.start": "Start",
    "title.continue": "Continue",
    "title.settings": "Settings",
    "title.playagain": "Play Again — from Night 1",
    "title.playagain.main": "Play Again",
    "title.playagain.sub": "from Night 1",
    "title.opentome": "Open the Tome",
    "title.playagain.confirm": "Start over from Night 1? Tonight's save will be replaced.",

    "herald.masthead": "The Arena Herald",
    "herald.continue": "— tap to continue —",

    "panel.tome.tooltip": "Open the Tome",
    "brew.base": "Base",
    "brew.mixer": "Mixer",
    "brew.none": "—",
    "brew.warmth": "Warmth",
    "brew.kick": "Kick",
    "brew.chill": "Chill",
    "brew.bite": "Bite",
    "brew.gentle": "Gentle",
    "brew.strong": "Strong",
    "brew.drops1": "1 drop",
    "brew.drops2": "2 drops",
    "brew.drops3": "3 drops",
    "brew.reset": "Reset",
    "brew.pour": "Pour",
    "brew.unnamed": "Unnamed mix",
    /* generic wrong-pour beat (GDD §7 no-silent-rejection) — used only when a
       gate has no bespoke `wrong:` line. {they} = the speaker's pronoun (cast.js).
       EN-only for now; other langs fall back to EN via t() (canon-term convention). */
    "brew.wrong.generic": "{they} slides the cup back, kindly.",
    "brew.locked": "Let them finish — the cup can wait.",
    "toast.nosave": "This browser can’t keep saves — tonight won’t be remembered.",
    /* in-game menu (§11, locked 07/07). EN populated; other langs fall back via t() until the localisation pass. */
    "menu.title": "Paused",
    "menu.resume": "Resume",
    "menu.tome": "The Tome",
    "menu.settings": "Settings",
    "menu.savequit": "Save & Quit",
    "menu.note": "The bar keeps your place — progress saves itself.",
    "autosave.saved": "Saved",
    "chip.tome": "Tap the Tome — your recipes live here.",
    "chip.ledger": "Tap the Tome — the Knight has a page now.",
    "continue.named": "Continue — {label}",
    "night.label": "Night {n}",
    "night.door": "Back to the door",

    /* Canon terms (GDD §13): Elixir, Dark Elixir and the six spells follow the
       OFFICIAL Clash Royale localisation. English is the canon here; each of
       the 6 languages gets its verified official term below (or, if a term
       can't be verified, it is simply OMITTED from that language and t() falls
       back to this English — the "stays English + flagged" rule, for free).
       Displayed via canonTerm() so the "×N" dose suffix survives. */
    "term.Elixir": "Elixir",
    "term.Dark Elixir": "Dark Elixir",
    "term.Water": "Water",   /* v1.6 third tap — English in every language until the localisation pass verifies official terms (the t() fallback handles the other six) */
    "term.Rage": "Rage",
    "term.Heal": "Heal",
    "term.Zap": "Zap",
    "term.Freeze": "Freeze",
    "term.Mirror": "Mirror",
    "term.Poison": "Poison",
    "ph.group.title": "The whole bar, one round",
    "ph.group.note": "Group scene lands in Milestone 6.",
    "ph.duo.title": "Two regulars, one counter",
    "ph.duo.note": "Split duologue lands in Milestone 6.",
    "ph.epilogue.title": "Last call",
    "ph.epilogue.note": "The epilogue lands in Milestone 6.",
    "ph.tome.title": "The Tome",
    "ph.tome.note": "Brew Book, Regulars' Ledger, Arena Herald and Bard's Songbook land in Milestone 5.",

    "night.complete": "Night {n} — closed up",
    "night.begin": "Begin Night {n}",
    "night.savequit": "Save & Quit",
    "nightcap.keep": "Keep Tonight's Page",
    "nightcap.night": "Night {n}",
    "nightcap.regulars": "Tonight's regulars",
    "nightcap.poured": "Poured tonight",
    "nightcap.flourish": "Same time tomorrow?",
    "nightcap.download": "Download",
    "nightcap.share": "Share",
    "nightcap.close": "Close",
    "nightcap.share.caption": "I tended the little bar on the border. You can too, at Elixir Hour.",
    "nightcap.share.copied": "Link copied.",
    "nightcap.share.copiedhand": "Send it to someone who needs to head to the bar!",
    "nightcap.share.copyfail": "Copy this link to share your night:",
    "nightcap.download.failed": "Couldn't save your Night Cap.",
    "nightcap.download.taint": "Saving only works from the shared link.",
    "nightcap.download.retry": "Something went wrong — give it another go.",
    "epilogue.totitle": "Back to the title",
    "epilogue.continue": "Continue ▸",   /* round 22: the mid-arc epilogue (after Night 3) flows on to Night 4 — English-only for now, t() falls back for the other six */
    "advance": "Next ▸",
    "tome.close": "✕",

    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.disclaimer": "English is hand-written. Other languages are AI-translated and may not be perfect.",
    "settings.music": "Music",
    "settings.sfx": "Sound effects",
    "settings.on": "On",
    "settings.off": "Off",
    "settings.about": "About / Credits",
    "settings.back": "Back",

    "about.title": "About Elixir Hour",
    "about.affiliation": "An original fan concept by Tessa Kerk. Not affiliated with or endorsed by Supercell. No Supercell code, art or copy is reproduced.",
    "about.translation": "English is hand-written. Other languages are AI-translated and may not be perfect.",
    "about.inspiration": "Inspired by the structure of Coffee Talk (Toge Productions) — an original story and cast, in tribute to the format.",
    "about.music": "The four bar tracks are AI-generated (Suno).",
    "audio.loading": "Music loading…",
  },

  ko: {
    "title.start": "시작",
    "title.continue": "이어하기",
    "title.settings": "설정",
    "herald.continue": "— 눌러서 계속 —",
    "night.complete": "밤 {n} — 영업 종료",
    "night.begin": "밤 {n} 시작",
    "night.savequit": "저장하고 나가기",
    "nightcap.keep": "오늘 밤의 페이지 보관하기",
    "nightcap.night": "밤 {n}",
    "nightcap.regulars": "오늘 밤의 단골들",
    "nightcap.poured": "오늘 밤 따른 술",
    "nightcap.flourish": "내일 또 볼까요?",
    "nightcap.download": "다운로드",
    "nightcap.share": "공유",
    "nightcap.close": "닫기",
    "epilogue.totitle": "타이틀로 돌아가기",
    "advance": "다음 ▸",
    "settings.title": "설정",
    "settings.language": "언어",
    "settings.disclaimer": "영어는 직접 작성된 원문입니다. 다른 언어는 AI 번역으로, 완벽하지 않을 수 있습니다.",
    "settings.music": "음악",
    "settings.sfx": "효과음",
    "settings.on": "켬",
    "settings.off": "끔",
    "settings.about": "정보 / 크레딧",
    "settings.back": "뒤로",
    "panel.tome.tooltip": "일지 열기",
    "brew.base": "베이스",
    "brew.mixer": "믹서",
    "brew.warmth": "온기",
    "brew.kick": "킥",
    "brew.chill": "냉기",
    "brew.bite": "쏘는 맛",
    "brew.gentle": "순하게",
    "brew.strong": "강하게",
    "brew.drops1": "1방울",
    "brew.drops2": "2방울",
    "brew.drops3": "3방울",
    "brew.reset": "초기화",
    "brew.pour": "따르기",
    "brew.unnamed": "이름 없는 조합",
    "toast.nosave": "이 브라우저는 저장할 수 없어요 — 오늘 밤은 기억되지 않아요.",
    "brew.locked": "이야기를 마치게 두세요 — 잔은 기다릴 수 있어요.",
    "menu.title": "일시정지",
    "menu.resume": "계속하기",
    "menu.tome": "일지",
    "menu.settings": "설정",
    "menu.savequit": "저장하고 나가기",
    "menu.note": "술집이 자리를 지켜줘요 — 진행은 자동으로 저장돼요.",
    "autosave.saved": "저장됨",
    "chip.tome": "일지를 누르세요 — 레시피가 여기 담겨요.",
    "chip.ledger": "일지를 누르세요 — 이제 기사의 페이지가 있어요.",
    "continue.named": "이어하기 — {label}",
    "night.label": "밤 {n}",
    "night.door": "문으로 돌아가기",
    "term.Elixir": "엘릭서",
    "term.Dark Elixir": "다크 엘릭서",
    "term.Rage": "분노 마법",
    "term.Heal": "치유 마법",
    "term.Zap": "감전 마법",
    "term.Mirror": "반사경",
    "term.Poison": "독 마법",
    /* Freeze: no official ko term verified → stays English (GDD §13) */
    "about.title": "Elixir Hour 정보",
    "about.affiliation": "Tessa Kerk의 오리지널 팬 창작물입니다. Supercell과 무관하며 Supercell의 승인을 받지 않았습니다. Supercell의 코드, 아트, 문구를 사용하지 않았습니다.",
    "about.translation": "영어는 직접 작성된 원문입니다. 다른 언어는 AI 번역으로, 완벽하지 않을 수 있습니다.",
    "about.inspiration": "Coffee Talk(Toge Productions)의 구성에서 영감을 받아, 오리지널 이야기와 등장인물로 만든 헌정작입니다.",
    "about.music": "네 곡의 바 음악은 AI로 생성되었습니다 (Suno).",
  },

  ja: {
    "title.start": "はじめる",
    "title.continue": "つづきから",
    "title.settings": "設定",
    "herald.continue": "— タップで続ける —",
    "night.complete": "夜 {n} — 店じまい",
    "night.begin": "夜 {n} を始める",
    "night.savequit": "セーブして終了",
    "nightcap.keep": "今夜のページを残す",
    "nightcap.night": "夜 {n}",
    "nightcap.regulars": "今夜の常連",
    "nightcap.poured": "今夜の一杯",
    "nightcap.flourish": "また明日、同じ時間に？",
    "nightcap.download": "ダウンロード",
    "nightcap.share": "共有",
    "nightcap.close": "閉じる",
    "epilogue.totitle": "タイトルへ戻る",
    "advance": "次へ ▸",
    "settings.title": "設定",
    "settings.language": "言語",
    "settings.disclaimer": "英語は手書きの原文です。他の言語はAI翻訳のため、完全ではない場合があります。",
    "settings.music": "音楽",
    "settings.sfx": "効果音",
    "settings.on": "オン",
    "settings.off": "オフ",
    "settings.about": "クレジット",
    "settings.back": "戻る",
    "panel.tome.tooltip": "手帳を開く",
    "brew.base": "ベース",
    "brew.mixer": "ミキサー",
    "brew.warmth": "温かさ",
    "brew.kick": "キック",
    "brew.chill": "冷たさ",
    "brew.bite": "刺激",
    "brew.gentle": "やさしく",
    "brew.strong": "強めに",
    "brew.drops1": "1滴",
    "brew.drops2": "2滴",
    "brew.drops3": "3滴",
    "brew.reset": "リセット",
    "brew.pour": "注ぐ",
    "brew.unnamed": "名もない一杯",
    "toast.nosave": "このブラウザは保存できません — 今夜のことは記憶されません。",
    "brew.locked": "話が終わるまで待ちましょう — 一杯は待てます。",
    "menu.title": "一時停止",
    "menu.resume": "再開",
    "menu.tome": "手帳",
    "menu.settings": "設定",
    "menu.savequit": "セーブして終了",
    "menu.note": "お店が席を取っておきます — 進行は自動で保存されます。",
    "autosave.saved": "保存しました",
    "chip.tome": "手帳をタップ — レシピはここに残ります。",
    "chip.ledger": "手帳をタップ — ナイトのページができました。",
    "continue.named": "つづきから — {label}",
    "night.label": "夜 {n}",
    "night.door": "扉に戻る",
    "term.Elixir": "エリクサー",
    "term.Dark Elixir": "ダークエリクサー",
    "term.Rage": "レイジ",
    "term.Heal": "ヒール",
    "term.Zap": "ザップ",
    "term.Freeze": "フリーズ",
    "term.Mirror": "鏡",
    "term.Poison": "ポイズン",
    "about.title": "Elixir Hour について",
    "about.affiliation": "Tessa Kerk によるオリジナルのファン作品です。Supercell とは無関係であり、Supercell の承認を受けていません。Supercell のコード・アート・文章は使用していません。",
    "about.translation": "英語は手書きの原文です。他の言語はAI翻訳のため、完全ではない場合があります。",
    "about.inspiration": "Coffee Talk（Toge Productions）の構成に着想を得た、オリジナルの物語とキャストによるオマージュ作品です。",
    "about.music": "4曲のバー音楽はAIで生成されています（Suno）。",
  },

  de: {
    "title.start": "Starten",
    "title.continue": "Fortsetzen",
    "title.settings": "Einstellungen",
    "herald.continue": "— zum Fortfahren tippen —",
    "night.complete": "Nacht {n} — Feierabend",
    "night.begin": "Nacht {n} beginnen",
    "night.savequit": "Speichern & Beenden",
    "nightcap.keep": "Die heutige Seite behalten",
    "nightcap.night": "Nacht {n}",
    "nightcap.regulars": "Die Gäste von heute Abend",
    "nightcap.poured": "Heute Abend ausgeschenkt",
    "nightcap.flourish": "Morgen zur selben Zeit?",
    "nightcap.download": "Herunterladen",
    "nightcap.share": "Teilen",
    "nightcap.close": "Schließen",
    "epilogue.totitle": "Zurück zum Titel",
    "advance": "Weiter ▸",
    "settings.title": "Einstellungen",
    "settings.language": "Sprache",
    "settings.disclaimer": "Englisch ist von Hand geschrieben. Andere Sprachen sind KI-übersetzt und möglicherweise nicht perfekt.",
    "settings.music": "Musik",
    "settings.sfx": "Soundeffekte",
    "settings.on": "An",
    "settings.off": "Aus",
    "settings.about": "Über / Credits",
    "settings.back": "Zurück",
    "panel.tome.tooltip": "Die Chronik öffnen",
    "brew.base": "Basis",
    "brew.mixer": "Mixer",
    "brew.warmth": "Wärme",
    "brew.kick": "Kick",
    "brew.chill": "Kühle",
    "brew.bite": "Biss",
    "brew.gentle": "Mild",
    "brew.strong": "Stark",
    "brew.drops1": "1 Tropfen",
    "brew.drops2": "2 Tropfen",
    "brew.drops3": "3 Tropfen",
    "brew.reset": "Zurücksetzen",
    "brew.pour": "Einschenken",
    "brew.unnamed": "Namenlose Mischung",
    "toast.nosave": "Dieser Browser kann nicht speichern — diese Nacht wird nicht erinnert.",
    "brew.locked": "Lass sie ausreden — der Becher kann warten.",
    "menu.title": "Pausiert",
    "menu.resume": "Fortsetzen",
    "menu.tome": "Die Chronik",
    "menu.settings": "Einstellungen",
    "menu.savequit": "Speichern & Beenden",
    "menu.note": "Die Bar hält deinen Platz frei — der Fortschritt speichert sich von selbst.",
    "autosave.saved": "Gespeichert",
    "chip.tome": "Tippe auf die Chronik — hier stehen deine Rezepte.",
    "chip.ledger": "Tippe auf die Chronik — der Ritter hat jetzt eine Seite.",
    "continue.named": "Fortsetzen — {label}",
    "night.label": "Nacht {n}",
    "night.door": "Zurück zur Tür",
    "term.Elixir": "Elixier",
    "term.Dark Elixir": "Dunkles Elixier",
    "term.Rage": "Wut",
    "term.Heal": "Heilung",
    "term.Zap": "Knall",
    "term.Freeze": "Frost",
    "term.Mirror": "Spiegel",
    "term.Poison": "Gift",
    "about.title": "Über Elixir Hour",
    "about.affiliation": "Ein originales Fan-Konzept von Tessa Kerk. Nicht mit Supercell verbunden und nicht von Supercell unterstützt. Es werden kein Code, keine Grafiken und keine Texte von Supercell verwendet.",
    "about.translation": "Englisch ist von Hand geschrieben. Andere Sprachen sind KI-übersetzt und möglicherweise nicht perfekt.",
    "about.inspiration": "Inspiriert vom Aufbau von Coffee Talk (Toge Productions) — mit eigener Geschichte und eigenem Ensemble, als Hommage an das Format.",
    "about.music": "Die vier Bar-Musikstücke sind KI-generiert (Suno).",
  },

  es: {
    "title.start": "Empezar",
    "title.continue": "Continuar",
    "title.settings": "Ajustes",
    "herald.continue": "— toca para continuar —",
    "night.complete": "Noche {n} — cerramos",
    "night.begin": "Empezar la noche {n}",
    "night.savequit": "Guardar y salir",
    "nightcap.keep": "Guardar la página de esta noche",
    "nightcap.night": "Noche {n}",
    "nightcap.regulars": "Los habituales de esta noche",
    "nightcap.poured": "Servido esta noche",
    "nightcap.flourish": "¿Mañana a la misma hora?",
    "nightcap.download": "Descargar",
    "nightcap.share": "Compartir",
    "nightcap.close": "Cerrar",
    "epilogue.totitle": "Volver al título",
    "advance": "Siguiente ▸",
    "settings.title": "Ajustes",
    "settings.language": "Idioma",
    "settings.disclaimer": "El inglés está escrito a mano. Los demás idiomas están traducidos por IA y pueden no ser perfectos.",
    "settings.music": "Música",
    "settings.sfx": "Efectos de sonido",
    "settings.on": "Activado",
    "settings.off": "Desactivado",
    "settings.about": "Acerca de / Créditos",
    "settings.back": "Atrás",
    "panel.tome.tooltip": "Abrir el tomo",
    "brew.base": "Base",
    "brew.mixer": "Mezclador",
    "brew.warmth": "Calidez",
    "brew.kick": "Intensidad",
    "brew.chill": "Frescor",
    "brew.bite": "Mordida",
    "brew.gentle": "Suave",
    "brew.strong": "Fuerte",
    "brew.drops1": "1 gota",
    "brew.drops2": "2 gotas",
    "brew.drops3": "3 gotas",
    "brew.reset": "Reiniciar",
    "brew.pour": "Servir",
    "brew.unnamed": "Mezcla sin nombre",
    "toast.nosave": "Este navegador no puede guardar — esta noche no se recordará.",
    "brew.locked": "Deja que terminen — la copa puede esperar.",
    "menu.title": "En pausa",
    "menu.resume": "Reanudar",
    "menu.tome": "El Tomo",
    "menu.settings": "Ajustes",
    "menu.savequit": "Guardar y salir",
    "menu.note": "La taberna te guarda el sitio — la partida se guarda sola.",
    "autosave.saved": "Guardado",
    "chip.tome": "Toca el Tomo — aquí están tus recetas.",
    "chip.ledger": "Toca el Tomo — el Caballero ya tiene una página.",
    "continue.named": "Continuar — {label}",
    "night.label": "Noche {n}",
    "night.door": "Volver a la puerta",
    /* Elixir: official es term IS "Elixir" (same as EN) → falls back. Dark Elixir: no official es term verified → stays English (GDD §13) */
    "term.Rage": "Furia",
    "term.Heal": "Curación",
    "term.Zap": "Descarga",
    "term.Freeze": "Hielo",
    "term.Mirror": "Espejo",
    "term.Poison": "Veneno",
    "about.title": "Acerca de Elixir Hour",
    "about.affiliation": "Un concepto fan original de Tessa Kerk. No está afiliado a Supercell ni cuenta con su respaldo. No se reproduce código, arte ni textos de Supercell.",
    "about.translation": "El inglés está escrito a mano. Los demás idiomas están traducidos por IA y pueden no ser perfectos.",
    "about.inspiration": "Inspirado en la estructura de Coffee Talk (Toge Productions): una historia y un reparto originales, en homenaje al formato.",
    "about.music": "Las cuatro pistas del bar están generadas por IA (Suno).",
  },

  fr: {
    "title.start": "Commencer",
    "title.continue": "Continuer",
    "title.settings": "Paramètres",
    "herald.continue": "— touchez pour continuer —",
    "night.complete": "Nuit {n} — on ferme",
    "night.begin": "Commencer la nuit {n}",
    "night.savequit": "Sauvegarder et quitter",
    "nightcap.keep": "Garder la page de ce soir",
    "nightcap.night": "Nuit {n}",
    "nightcap.regulars": "Les habitués de ce soir",
    "nightcap.poured": "Servi ce soir",
    "nightcap.flourish": "Demain, à la même heure ?",
    "nightcap.download": "Télécharger",
    "nightcap.share": "Partager",
    "nightcap.close": "Fermer",
    "epilogue.totitle": "Retour au titre",
    "advance": "Suivant ▸",
    "settings.title": "Paramètres",
    "settings.language": "Langue",
    "settings.disclaimer": "L'anglais est écrit à la main. Les autres langues sont traduites par IA et peuvent être imparfaites.",
    "settings.music": "Musique",
    "settings.sfx": "Effets sonores",
    "settings.on": "Activé",
    "settings.off": "Désactivé",
    "settings.about": "À propos / Crédits",
    "settings.back": "Retour",
    "panel.tome.tooltip": "Ouvrir le Tome",
    "brew.base": "Base",
    "brew.mixer": "Mixeur",
    "brew.warmth": "Chaleur",
    "brew.kick": "Punch",
    "brew.chill": "Fraîcheur",
    "brew.bite": "Mordant",
    "brew.gentle": "Doux",
    "brew.strong": "Fort",
    "brew.drops1": "1 goutte",
    "brew.drops2": "2 gouttes",
    "brew.drops3": "3 gouttes",
    "brew.reset": "Réinitialiser",
    "brew.pour": "Verser",
    "brew.unnamed": "Mélange sans nom",
    "toast.nosave": "Ce navigateur ne peut pas sauvegarder — cette nuit ne sera pas gardée en mémoire.",
    "brew.locked": "Laisse-les finir — la chope peut attendre.",
    "menu.title": "En pause",
    "menu.resume": "Reprendre",
    "menu.tome": "Le Tome",
    "menu.settings": "Paramètres",
    "menu.savequit": "Sauvegarder et quitter",
    "menu.note": "Le bar garde ta place — la progression se sauvegarde toute seule.",
    "autosave.saved": "Sauvegardé",
    "chip.tome": "Touche le Tome — tes recettes sont ici.",
    "chip.ledger": "Touche le Tome — le Chevalier a une page maintenant.",
    "continue.named": "Continuer — {label}",
    "night.label": "Nuit {n}",
    "night.door": "Retour à la porte",
    "term.Elixir": "Élixir",
    "term.Dark Elixir": "Élixir noir",
    "term.Freeze": "Gel",
    "term.Mirror": "Miroir",
    /* Rage + Poison: official fr terms ARE "Rage"/"Poison" (same as EN) → fall back. Heal + Zap: no official fr term verified → stay English (GDD §13) */
    "about.title": "À propos d'Elixir Hour",
    "about.affiliation": "Un concept de fan original de Tessa Kerk. Sans affiliation avec Supercell et non approuvé par Supercell. Aucun code, art ou texte de Supercell n'est reproduit.",
    "about.translation": "L'anglais est écrit à la main. Les autres langues sont traduites par IA et peuvent être imparfaites.",
    "about.inspiration": "Inspiré de la structure de Coffee Talk (Toge Productions) — une histoire et une distribution originales, en hommage au format.",
    "about.music": "Les quatre morceaux du bar sont générés par IA (Suno).",
  },

  pt: {
    "title.start": "Começar",
    "title.continue": "Continuar",
    "title.settings": "Configurações",
    "herald.continue": "— toque para continuar —",
    "night.complete": "Noite {n} — fechamos",
    "night.begin": "Começar a noite {n}",
    "night.savequit": "Salvar e sair",
    "nightcap.keep": "Guardar a página desta noite",
    "nightcap.night": "Noite {n}",
    "nightcap.regulars": "Os frequentadores desta noite",
    "nightcap.poured": "Servido esta noite",
    "nightcap.flourish": "Amanhã na mesma hora?",
    "nightcap.download": "Baixar",
    "nightcap.share": "Compartilhar",
    "nightcap.close": "Fechar",
    "epilogue.totitle": "Voltar ao título",
    "advance": "Próximo ▸",
    "settings.title": "Configurações",
    "settings.language": "Idioma",
    "settings.disclaimer": "O inglês foi escrito à mão. Os outros idiomas são traduzidos por IA e podem não ser perfeitos.",
    "settings.music": "Música",
    "settings.sfx": "Efeitos sonoros",
    "settings.on": "Ativado",
    "settings.off": "Desativado",
    "settings.about": "Sobre / Créditos",
    "settings.back": "Voltar",
    "panel.tome.tooltip": "Abrir o tomo",
    "brew.base": "Base",
    "brew.mixer": "Mistura",
    "brew.warmth": "Calor",
    "brew.kick": "Intensidade",
    "brew.chill": "Frescor",
    "brew.bite": "Mordida",
    "brew.gentle": "Suave",
    "brew.strong": "Forte",
    "brew.drops1": "1 gota",
    "brew.drops2": "2 gotas",
    "brew.drops3": "3 gotas",
    "brew.reset": "Redefinir",
    "brew.pour": "Servir",
    "brew.unnamed": "Mistura sem nome",
    "toast.nosave": "Este navegador não consegue guardar — esta noite não será lembrada.",
    "brew.locked": "Deixe-os terminar — a caneca pode esperar.",
    "menu.title": "Em pausa",
    "menu.resume": "Retomar",
    "menu.tome": "O Tomo",
    "menu.settings": "Configurações",
    "menu.savequit": "Salvar e sair",
    "menu.note": "O bar guarda o teu lugar — o progresso salva-se sozinho.",
    "autosave.saved": "Salvo",
    "chip.tome": "Toque no Tomo — as suas receitas ficam aqui.",
    "chip.ledger": "Toque no Tomo — o Cavaleiro agora tem uma página.",
    "continue.named": "Continuar — {label}",
    "night.label": "Noite {n}",
    "night.door": "Voltar à porta",
    /* Elixir: official pt-BR term IS "Elixir" (same as EN) → falls back */
    "term.Dark Elixir": "Elixir Negro",
    "term.Rage": "Fúria",
    "term.Zap": "Choque",
    "term.Mirror": "Espelho",
    "term.Poison": "Veneno",
    /* Heal + Freeze: no official pt term verified → stay English (GDD §13) */
    "about.title": "Sobre Elixir Hour",
    "about.affiliation": "Um conceito original de fã por Tessa Kerk. Sem afiliação com a Supercell e sem endosso da Supercell. Nenhum código, arte ou texto da Supercell é reproduzido.",
    "about.translation": "O inglês foi escrito à mão. Os outros idiomas são traduzidos por IA e podem não ser perfeitos.",
    "about.inspiration": "Inspirado na estrutura de Coffee Talk (Toge Productions) — uma história e um elenco originais, em homenagem ao formato.",
    "about.music": "As quatro faixas do bar são geradas por IA (Suno).",
  },
};
window.LANG = "en";

/* t(key, {n:2}) — looks up the current language, falls back to English,
   then to the key itself so missing strings are visible, never fatal. */
window.t = function (key, vars) {
  var table = window.STRINGS[window.LANG] || {};
  var s = table[key] != null ? table[key]
        : (window.STRINGS.en[key] != null ? window.STRINGS.en[key] : key);
  if (vars) for (var k in vars) s = s.split("{" + k + "}").join(vars[k]);
  return s;
};

/* canonTerm(name) — the official Clash Royale localisation of a canon term
   (GDD §13). Splits a trailing "×N" dose suffix so "Heal ×2" localises its
   Heal and keeps the ×2. Unlocalised terms fall back to English via t(). */
window.canonTerm = function (name) {
  if (!name) return name;
  var m = String(name).match(/^(.*?)(\s*×\s*\d+)\s*$/);
  if (m) return t("term." + m[1].trim()) + m[2];
  return t("term." + name);
};
