/* All player-facing text lives in string tables (GDD §13). English is the
   hand-written original; the other six are AI-translated (see the in-product
   disclaimer in Settings/About). Classic script + window globals on purpose:
   the game must run from file://, which blocks ES modules and fetch() of JSON.

   UI chrome is translated below. Narrative content (Herald copy, dialogue,
   Tome entries) is translated with its content milestones, not here.
   The ph.* placeholder notes are dev scaffolding and stay English. */

window.LANGS = [
  { code: "en", native: "English" },
  { code: "ko", native: "한국어" },
  { code: "ja", native: "日本語" },
  { code: "de", native: "Deutsch" },
  { code: "es", native: "Español" },
  { code: "fr", native: "Français" },
  { code: "pt", native: "Português" },
];

window.STRINGS = {
  en: {
    "title.start": "Start",
    "title.continue": "Continue",
    "title.settings": "Settings",

    "herald.masthead": "The Arena Herald",
    "herald.continue": "— tap to continue —",

    "panel.tome.tooltip": "Open the Tome",
    "brew.base": "Base",
    "brew.mixer": "Mixer",
    "brew.none": "—",
    "brew.warmth": "Warmth",
    "brew.kick": "Kick",
    "brew.chill": "Chill",
    "brew.bite": "Bite",
    "brew.gentle": "Gentle",
    "brew.strong": "Strong",
    "brew.reset": "Reset",
    "brew.pour": "Pour",
    "brew.unnamed": "Unnamed mix",
    "ph.group.title": "The whole bar, one round",
    "ph.group.note": "Group scene lands in Milestone 6.",
    "ph.duo.title": "Two regulars, one counter",
    "ph.duo.note": "Split duologue lands in Milestone 6.",
    "ph.epilogue.title": "Last call",
    "ph.epilogue.note": "The epilogue lands in Milestone 6.",
    "ph.tome.title": "The Tome",
    "ph.tome.note": "Brew Book, Regulars' Ledger, Arena Herald and Bard's Songbook land in Milestone 5.",

    "night.complete": "Night {n} — closed up",
    "night.begin": "Begin Night {n}",
    "night.savequit": "Save & Quit",
    "epilogue.totitle": "Back to the title",
    "advance": "Next ▸",
    "tome.close": "✕",

    "settings.title": "Settings",
    "settings.language": "Language",
    "settings.disclaimer": "English is hand-written. Other languages are AI-translated and may not be perfect.",
    "settings.music": "Music",
    "settings.sfx": "Sound effects",
    "settings.on": "On",
    "settings.off": "Off",
    "settings.about": "About / Credits",
    "settings.back": "Back",

    "about.title": "About Elixir Hour",
    "about.affiliation": "An original fan concept by Tessa Kerk. Not affiliated with or endorsed by Supercell. No Supercell code, art or copy is reproduced.",
    "about.translation": "English is hand-written. Other languages are AI-translated and may not be perfect.",
    "about.inspiration": "Inspired by the structure of Coffee Talk (Toge Productions) — an original story and cast, in tribute to the format.",
  },

  ko: {
    "title.start": "시작",
    "title.continue": "이어하기",
    "title.settings": "설정",
    "herald.continue": "— 눌러서 계속 —",
    "night.complete": "밤 {n} — 영업 종료",
    "night.begin": "밤 {n} 시작",
    "night.savequit": "저장하고 나가기",
    "epilogue.totitle": "타이틀로 돌아가기",
    "advance": "다음 ▸",
    "settings.title": "설정",
    "settings.language": "언어",
    "settings.disclaimer": "영어는 직접 작성된 원문입니다. 다른 언어는 AI 번역으로, 완벽하지 않을 수 있습니다.",
    "settings.music": "음악",
    "settings.sfx": "효과음",
    "settings.on": "켬",
    "settings.off": "끔",
    "settings.about": "정보 / 크레딧",
    "settings.back": "뒤로",
    "panel.tome.tooltip": "기록서 열기",
    "brew.base": "베이스",
    "brew.mixer": "믹서",
    "brew.warmth": "온기",
    "brew.kick": "킥",
    "brew.chill": "냉기",
    "brew.bite": "쏘는 맛",
    "brew.gentle": "순하게",
    "brew.strong": "강하게",
    "brew.reset": "초기화",
    "brew.pour": "따르기",
    "brew.unnamed": "이름 없는 조합",
    "about.title": "Elixir Hour 정보",
    "about.affiliation": "Tessa Kerk의 오리지널 팬 창작물입니다. Supercell과 무관하며 Supercell의 승인을 받지 않았습니다. Supercell의 코드, 아트, 문구를 사용하지 않았습니다.",
    "about.translation": "영어는 직접 작성된 원문입니다. 다른 언어는 AI 번역으로, 완벽하지 않을 수 있습니다.",
    "about.inspiration": "Coffee Talk(Toge Productions)의 구성에서 영감을 받아, 오리지널 이야기와 등장인물로 만든 헌정작입니다.",
  },

  ja: {
    "title.start": "はじめる",
    "title.continue": "つづきから",
    "title.settings": "設定",
    "herald.continue": "— タップで続ける —",
    "night.complete": "夜 {n} — 店じまい",
    "night.begin": "夜 {n} を始める",
    "night.savequit": "セーブして終了",
    "epilogue.totitle": "タイトルへ戻る",
    "advance": "次へ ▸",
    "settings.title": "設定",
    "settings.language": "言語",
    "settings.disclaimer": "英語は手書きの原文です。他の言語はAI翻訳のため、完全ではない場合があります。",
    "settings.music": "音楽",
    "settings.sfx": "効果音",
    "settings.on": "オン",
    "settings.off": "オフ",
    "settings.about": "クレジット",
    "settings.back": "戻る",
    "panel.tome.tooltip": "記録帳を開く",
    "brew.base": "ベース",
    "brew.mixer": "ミキサー",
    "brew.warmth": "温かさ",
    "brew.kick": "キック",
    "brew.chill": "冷たさ",
    "brew.bite": "刺激",
    "brew.gentle": "やさしく",
    "brew.strong": "強めに",
    "brew.reset": "リセット",
    "brew.pour": "注ぐ",
    "brew.unnamed": "名もない一杯",
    "about.title": "Elixir Hour について",
    "about.affiliation": "Tessa Kerk によるオリジナルのファン作品です。Supercell とは無関係であり、Supercell の承認を受けていません。Supercell のコード・アート・文章は使用していません。",
    "about.translation": "英語は手書きの原文です。他の言語はAI翻訳のため、完全ではない場合があります。",
    "about.inspiration": "Coffee Talk（Toge Productions）の構成に着想を得た、オリジナルの物語とキャストによるオマージュ作品です。",
  },

  de: {
    "title.start": "Starten",
    "title.continue": "Fortsetzen",
    "title.settings": "Einstellungen",
    "herald.continue": "— zum Fortfahren tippen —",
    "night.complete": "Nacht {n} — Feierabend",
    "night.begin": "Nacht {n} beginnen",
    "night.savequit": "Speichern & Beenden",
    "epilogue.totitle": "Zurück zum Titel",
    "advance": "Weiter ▸",
    "settings.title": "Einstellungen",
    "settings.language": "Sprache",
    "settings.disclaimer": "Englisch ist von Hand geschrieben. Andere Sprachen sind KI-übersetzt und möglicherweise nicht perfekt.",
    "settings.music": "Musik",
    "settings.sfx": "Soundeffekte",
    "settings.on": "An",
    "settings.off": "Aus",
    "settings.about": "Über / Credits",
    "settings.back": "Zurück",
    "panel.tome.tooltip": "Das Buch öffnen",
    "brew.base": "Basis",
    "brew.mixer": "Mixer",
    "brew.warmth": "Wärme",
    "brew.kick": "Kick",
    "brew.chill": "Kühle",
    "brew.bite": "Biss",
    "brew.gentle": "Mild",
    "brew.strong": "Stark",
    "brew.reset": "Zurücksetzen",
    "brew.pour": "Einschenken",
    "brew.unnamed": "Namenlose Mischung",
    "about.title": "Über Elixir Hour",
    "about.affiliation": "Ein originales Fan-Konzept von Tessa Kerk. Nicht mit Supercell verbunden und nicht von Supercell unterstützt. Es werden kein Code, keine Grafiken und keine Texte von Supercell verwendet.",
    "about.translation": "Englisch ist von Hand geschrieben. Andere Sprachen sind KI-übersetzt und möglicherweise nicht perfekt.",
    "about.inspiration": "Inspiriert vom Aufbau von Coffee Talk (Toge Productions) — mit eigener Geschichte und eigenem Ensemble, als Hommage an das Format.",
  },

  es: {
    "title.start": "Empezar",
    "title.continue": "Continuar",
    "title.settings": "Ajustes",
    "herald.continue": "— toca para continuar —",
    "night.complete": "Noche {n} — cerramos",
    "night.begin": "Empezar la noche {n}",
    "night.savequit": "Guardar y salir",
    "epilogue.totitle": "Volver al título",
    "advance": "Siguiente ▸",
    "settings.title": "Ajustes",
    "settings.language": "Idioma",
    "settings.disclaimer": "El inglés está escrito a mano. Los demás idiomas están traducidos por IA y pueden no ser perfectos.",
    "settings.music": "Música",
    "settings.sfx": "Efectos de sonido",
    "settings.on": "Activado",
    "settings.off": "Desactivado",
    "settings.about": "Acerca de / Créditos",
    "settings.back": "Atrás",
    "panel.tome.tooltip": "Abrir el tomo",
    "brew.base": "Base",
    "brew.mixer": "Mezclador",
    "brew.warmth": "Calidez",
    "brew.kick": "Intensidad",
    "brew.chill": "Frescor",
    "brew.bite": "Mordida",
    "brew.gentle": "Suave",
    "brew.strong": "Fuerte",
    "brew.reset": "Reiniciar",
    "brew.pour": "Servir",
    "brew.unnamed": "Mezcla sin nombre",
    "about.title": "Acerca de Elixir Hour",
    "about.affiliation": "Un concepto fan original de Tessa Kerk. No está afiliado a Supercell ni cuenta con su respaldo. No se reproduce código, arte ni textos de Supercell.",
    "about.translation": "El inglés está escrito a mano. Los demás idiomas están traducidos por IA y pueden no ser perfectos.",
    "about.inspiration": "Inspirado en la estructura de Coffee Talk (Toge Productions): una historia y un reparto originales, en homenaje al formato.",
  },

  fr: {
    "title.start": "Commencer",
    "title.continue": "Continuer",
    "title.settings": "Paramètres",
    "herald.continue": "— touchez pour continuer —",
    "night.complete": "Nuit {n} — on ferme",
    "night.begin": "Commencer la nuit {n}",
    "night.savequit": "Sauvegarder et quitter",
    "epilogue.totitle": "Retour au titre",
    "advance": "Suivant ▸",
    "settings.title": "Paramètres",
    "settings.language": "Langue",
    "settings.disclaimer": "L'anglais est écrit à la main. Les autres langues sont traduites par IA et peuvent être imparfaites.",
    "settings.music": "Musique",
    "settings.sfx": "Effets sonores",
    "settings.on": "Activé",
    "settings.off": "Désactivé",
    "settings.about": "À propos / Crédits",
    "settings.back": "Retour",
    "panel.tome.tooltip": "Ouvrir le registre",
    "brew.base": "Base",
    "brew.mixer": "Mixeur",
    "brew.warmth": "Chaleur",
    "brew.kick": "Punch",
    "brew.chill": "Fraîcheur",
    "brew.bite": "Mordant",
    "brew.gentle": "Doux",
    "brew.strong": "Fort",
    "brew.reset": "Réinitialiser",
    "brew.pour": "Verser",
    "brew.unnamed": "Mélange sans nom",
    "about.title": "À propos d'Elixir Hour",
    "about.affiliation": "Un concept de fan original de Tessa Kerk. Sans affiliation avec Supercell et non approuvé par Supercell. Aucun code, art ou texte de Supercell n'est reproduit.",
    "about.translation": "L'anglais est écrit à la main. Les autres langues sont traduites par IA et peuvent être imparfaites.",
    "about.inspiration": "Inspiré de la structure de Coffee Talk (Toge Productions) — une histoire et une distribution originales, en hommage au format.",
  },

  pt: {
    "title.start": "Começar",
    "title.continue": "Continuar",
    "title.settings": "Configurações",
    "herald.continue": "— toque para continuar —",
    "night.complete": "Noite {n} — fechamos",
    "night.begin": "Começar a noite {n}",
    "night.savequit": "Salvar e sair",
    "epilogue.totitle": "Voltar ao título",
    "advance": "Próximo ▸",
    "settings.title": "Configurações",
    "settings.language": "Idioma",
    "settings.disclaimer": "O inglês foi escrito à mão. Os outros idiomas são traduzidos por IA e podem não ser perfeitos.",
    "settings.music": "Música",
    "settings.sfx": "Efeitos sonoros",
    "settings.on": "Ativado",
    "settings.off": "Desativado",
    "settings.about": "Sobre / Créditos",
    "settings.back": "Voltar",
    "panel.tome.tooltip": "Abrir o tomo",
    "brew.base": "Base",
    "brew.mixer": "Mistura",
    "brew.warmth": "Calor",
    "brew.kick": "Intensidade",
    "brew.chill": "Frescor",
    "brew.bite": "Mordida",
    "brew.gentle": "Suave",
    "brew.strong": "Forte",
    "brew.reset": "Redefinir",
    "brew.pour": "Servir",
    "brew.unnamed": "Mistura sem nome",
    "about.title": "Sobre Elixir Hour",
    "about.affiliation": "Um conceito original de fã por Tessa Kerk. Sem afiliação com a Supercell e sem endosso da Supercell. Nenhum código, arte ou texto da Supercell é reproduzido.",
    "about.translation": "O inglês foi escrito à mão. Os outros idiomas são traduzidos por IA e podem não ser perfeitos.",
    "about.inspiration": "Inspirado na estrutura de Coffee Talk (Toge Productions) — uma história e um elenco originais, em homenagem ao formato.",
  },
};
window.LANG = "en";

/* t(key, {n:2}) — looks up the current language, falls back to English,
   then to the key itself so missing strings are visible, never fatal. */
window.t = function (key, vars) {
  var table = window.STRINGS[window.LANG] || {};
  var s = table[key] != null ? table[key]
        : (window.STRINGS.en[key] != null ? window.STRINGS.en[key] : key);
  if (vars) for (var k in vars) s = s.split("{" + k + "}").join(vars[k]);
  return s;
};
